const flowWithFault = {
    geometry: {},
    isTerminal: true,
    layoutConfig: {},
    nodes: [
        {
            config: {},
            flows: [],
            guid: 'start',
            isNew: false,
            isTerminal: false,
            label: undefined,
            logicConnectors: [],
            menuOpened: false,
            metadata: {
                canHaveFaultConnector: false,
                description: 'Screen Flow',
                elementType: 'START_ELEMENT',
                hasContext: false,
                hasTrigger: false,
                icon: 'utility:right',
                iconBackgroundColor: 'background-green',
                iconShape: 'circle',
                iconSize: 'medium',
                isSupported: true,
                label: 'Start',
                section: null,
                supportsMenu: true,
                type: 'start',
                value: 'START_ELEMENT'
            },
            nextConnector: {
                addInfo: {
                    menuOpened: false,
                    offsetY: 60
                },
                connectionInfo: {
                    next: 'decision',
                    prev: 'start'
                },
                geometry: {},
                goToTargetLabel: undefined,
                isFault: undefined,
                isHighlighted: false,
                labelOffsetY: 48,
                labelType: 0,
                svgInfo: {
                    endLocation: { x: 3, y: 120 },
                    geometry: {},
                    path: 'M 3, 0\nL 3, 120'
                },
                toBeDeleted: false,
                type: 'straight'
            },
            node: {
                availableConnections: [],
                childIndex: 0,
                childReferences: [],
                config: {},
                connectorCount: 0,
                description: '',
                elementType: 'START_ELEMENT',
                filterLogic: 'and',
                filters: [],
                guid: 'start',
                isCanvasElement: true,
                isTerminal: true,
                locationX: 50,
                locationY: 50,
                maxConnections: 1,
                next: 'decision',
                nodeType: 'start',
                object: '',
                objectIndex: 'df15cf8a-56d1-45df-92e8-9f9504077522',
                parent: 'root',
                prev: null,
                triggerType: 'None'
            },
            toBeDeleted: false
        },
        {
            conditionOptions: [],
            config: {},
            defaultConnectorLabel: 'Default Outcome',
            flows: [
                {
                    geometry: {},
                    isTerminal: false,
                    layoutConfig: {},
                    nodes: [],
                    preConnector: {
                        addInfo: { offsetY: 84, menuOpened: false },
                        connectionInfo: { parent: 'decision', childIndex: 0 },
                        connectorBadgeLabel: 'o1',
                        geometry: {},
                        goToTargetLabel: undefined,
                        isFault: false,
                        isHighlighted: false,
                        labelOffsetY: 48,
                        labelType: 1,
                        svgInfo: {
                            endLocation: { x: 3, y: 96 },
                            geometry: {},
                            path: 'M 3, 24↵L 3, 96'
                        },
                        toBeDeleted: false,
                        type: 'straight'
                    }
                },
                {
                    geometry: {},
                    isTerminal: false,
                    layoutConfig: {},
                    nodes: [],
                    preConnector: {
                        addInfo: { offsetY: 84, menuOpened: false },
                        connectionInfo: { parent: 'decision', childIndex: 1 },
                        connectorBadgeLabel: 'Default Outcome',
                        geometry: {},
                        goToTargetLabel: undefined,
                        isFault: false,
                        isHighlighted: false,
                        labelOffsetY: 48,
                        labelType: 1,
                        svgInfo: {
                            endLocation: { x: 3, y: 96 },
                            geometry: {},
                            path: 'M 3, 24\nL 3, 96'
                        },
                        toBeDeleted: false,
                        type: 'straight'
                    }
                }
            ],
            geometry: {},
            guid: 'decision',
            isNew: false,
            isTerminal: false,
            label: 'decision',
            logicConnectors: [],
            menuOpened: false,
            metadata: {
                canHaveFaultConnector: undefined,
                description: 'Create paths for the flow to take based on conditions you set.',
                dynamicNodeComponent: undefined,
                dynamicNodeComponentSelector: undefined,
                elementType: 'Decision',
                icon: 'standard:decision',
                iconBackgroundColor: undefined,
                iconShape: 'diamond',
                iconSize: undefined,
                isSupported: true,
                label: 'Decision',
                section: 'Logic',
                supportsMenu: true,
                type: 'branch',
                value: 'Decision'
            },
            nextConnector: {
                addInfo: { offsetY: 36, menuOpened: false },
                connectionInfo: {
                    prev: 'decision',
                    next: 'createRecords'
                },
                geometry: {},
                goToTargetLabel: undefined,
                isFault: undefined,
                isHighlighted: false,
                labelOffsetY: 48,
                labelType: 0,
                svgInfo: {
                    endLocation: { x: 3, y: 144 },
                    geometry: {},
                    path: 'M 3, 24\nL 3, 144'
                },
                toBeDeleted: false,
                type: 'straight'
            },
            node: {
                availableConnections: [],
                childReferences: [{ childReference: 'ed3e7c01-fb00-4f40-a7d3-89a3887fa20c' }],
                children: [null, null],
                config: {},
                connectorCount: 0,
                defaultConnectorLabel: 'Default Outcome',
                description: '',
                elementSubtype: null,
                elementType: 'Decision',
                guid: 'decision',
                incomingGoTo: [],
                isCanvasElement: true,
                label: 'decision',
                locationX: 0,
                locationY: 0,
                maxConnections: 2,
                name: 'decision',
                next: 'createRecords',
                nodeType: 'branch',
                prev: 'start'
            },
            toBeDeleted: false
        },
        {
            conditionOptions: undefined,
            config: {},
            defaultConnectorLabel: undefined,
            faultFlow: {
                geometry: {},
                isTerminal: true,
                layoutConfig: {},
                nodes: [
                    {
                        config: {},
                        flows: [],
                        geometry: {},
                        guid: 'screen',
                        isNew: false,
                        isTerminal: false,
                        label: 'screen',
                        logicConnectors: [],
                        menuOpened: true,
                        metadata: {
                            canHaveFaultConnector: undefined,
                            description:
                                'Collect information from users who run the flow or show them some information.',
                            dynamicNodeComponent: undefined,
                            dynamicNodeComponentSelector: undefined,
                            elementType: 'Screen',
                            icon: 'standard:screen',
                            iconBackgroundColor: undefined,
                            iconShape: undefined,
                            iconSize: undefined,
                            isSupported: true,
                            label: 'Screen',
                            section: 'Interaction',
                            supportsMenu: true,
                            type: 'default',
                            value: 'Screen'
                        },
                        nextConnector: {
                            addInfo: { offsetY: 60, menuOpened: false },
                            connectionInfo: { prev: 'screen', next: 'faultEnd' },
                            geometry: {},
                            goToTargetLabel: undefined,
                            isFault: undefined,
                            isHighlighted: false,
                            labelOffsetY: 48,
                            labelType: 0,
                            svgInfo: {
                                endLocation: { x: 3, y: 120 },
                                geometry: {},
                                path: 'M 3, 0\nL 3, 120'
                            },
                            toBeDeleted: false,
                            type: 'straight'
                        },
                        node: {
                            allowBack: true,
                            allowCustomPauseMessage: false,
                            allowFinish: true,
                            allowHelp: false,
                            allowPause: true,
                            backLabel: null,
                            backLabelType: 'standard',
                            childIndex: -1,
                            childReferences: [],
                            config: {},
                            connectorCount: 0,
                            description: '',
                            elementSubtype: null,
                            elementType: 'Screen',
                            guid: 'screen',
                            helpText: '',
                            incomingGoTo: [],
                            isCanvasElement: true,
                            isTerminal: true,
                            label: 'screen',
                            locationX: 0,
                            locationY: 0,
                            maxConnections: 1,
                            name: 'screen',
                            next: 'faultEnd',
                            nextOrFinishLabel: null,
                            nextOrFinishLabelType: 'standard',
                            nodeType: 'default',
                            parent: 'createRecords',
                            pauseLabel: null,
                            pauseLabelType: 'standard',
                            pausedText: '',
                            prev: null,
                            showFooter: true,
                            showHeader: true
                        },
                        toBeDeleted: false
                    },
                    {
                        config: [],
                        flows: [],
                        geometry: {},
                        guid: 'faultEnd',
                        isNew: false,
                        isTerminal: true,
                        label: 'End',
                        logicConnectors: [],
                        menuOpened: false,
                        metadata: {
                            canHaveFaultConnector: false,
                            description: 'Finish the flow.',
                            elementType: 'END_ELEMENT',
                            icon: 'utility:stop',
                            iconBackgroundColor: 'background-red',
                            iconShape: 'circle',
                            iconSize: 'medium',
                            isSupported: true,
                            label: 'End',
                            section: 'Logic',
                            supportsMenu: false,
                            type: 'end',
                            value: 'END_ELEMENT'
                        },
                        node: {
                            config: {},
                            connectorCount: 0,
                            description: '',
                            elementType: 'END_ELEMENT',
                            guid: 'faultEnd',
                            isCanvasElement: true,
                            isTerminal: true,
                            label: 'End',
                            locationX: 0,
                            locationY: 0,
                            name: 'END_ELEMENT',
                            next: null,
                            nodeType: 'end',
                            prev: 'screen',
                            text: 'END_ELEMENT',
                            value: 'END_ELEMENT'
                        },
                        toBeDeleted: false
                    }
                ],
                preConnector: {
                    addInfo: { offsetY: 60, menuOpened: false },
                    connectionInfo: { parent: 'createRecords', childIndex: -1 },
                    geometry: {},
                    goToTargetLabel: undefined,
                    isFault: true,
                    isHighlighted: false,
                    labelOffsetY: 24,
                    labelType: 4,
                    svgInfo: {
                        endLocation: { x: 3, y: 120 },
                        geometry: {},
                        path: 'M 3, 24\nL 3, 120'
                    },
                    toBeDeleted: false,
                    type: 'straight'
                }
            },
            flows: [],
            geometry: {},
            guid: 'createRecords',
            isNew: false,
            isTerminal: false,
            label: 'createRecords',
            logicConnectors: [
                {
                    connectionInfo: { parent: 'root', childIndex: -1 },
                    geometry: {},
                    isFault: true,
                    isHighlighted: false,
                    labelType: 0,
                    svgInfo: {
                        endLocation: { x: 267, y: 27 },
                        geometry: {},
                        path: 'M 3, 3\nL 251, 3\nA 16 16 0 0 1, 267, 19\nL 267, 27'
                    },
                    toBeDeleted: false,
                    type: 'branchRight'
                }
            ],
            menuOpened: false,
            metadata: {
                canHaveFaultConnector: true,
                description: 'Create Salesforce records using values from the flow.',
                dynamicNodeComponent: undefined,
                dynamicNodeComponentSelector: undefined,
                elementType: 'RecordCreate',
                icon: 'standard:record_create',
                iconBackgroundColor: undefined,
                iconShape: undefined,
                iconSize: undefined,
                isSupported: true,
                label: 'Create Records',
                section: 'Data',
                supportsMenu: true,
                type: 'default',
                value: 'RecordCreate'
            },
            nextConnector: {
                addInfo: { offsetY: 60, menuOpened: false },
                connectionInfo: {
                    prev: 'createRecords',
                    next: 'end'
                },
                geometry: {},
                goToTargetLabel: undefined,
                isFault: undefined,
                isHighlighted: false,
                labelOffsetY: 48,
                labelType: 0,
                svgInfo: {
                    endLocation: { x: 3, y: 120 },
                    geometry: {},
                    path: 'M 3, 0\nL 3, 120'
                },
                toBeDeleted: false,
                type: 'straight'
            },
            node: {
                alcInsertAt: { prev: 'decision' },
                assignRecordIdToReference: '',
                assignRecordIdToReferenceIndex: '6b4d0784-4073-42fc-9941-d32af5b035ec',
                availableConnections: [],
                config: {},
                connectorCount: 0,
                dataType: 'String',
                description: '',
                elementSubtype: null,
                elementType: 'RecordCreate',
                fault: 'faultEnd',
                getFirstRecordOnly: true,
                guid: 'createRecords',
                incomingGoTo: [],
                inputAssignments: [],
                inputReference: '',
                inputReferenceIndex: '2f174ea6-79b4-4fe4-9915-1e7bb21525d0',
                isAddingResourceViaLeftPanel: false,
                isCanvasElement: true,
                label: 'createRecords',
                locationX: 0,
                locationY: 0,
                maxConnections: 2,
                name: 'createRecords',
                next: 'end',
                nodeType: 'default',
                object: 'Account',
                objectIndex: 'd128defa-2a23-4c61-a72e-cdd628173b2c',
                prev: 'decision',
                storeOutputAutomatically: true
            },
            toBeDeleted: false
        },
        {
            config: {},
            flows: [],
            geometry: {},
            guid: 'end',
            isNew: false,
            isTerminal: true,
            label: 'End',
            logicConnectors: [],
            menuOpened: false,
            metadata: {
                canHaveFaultConnector: false,
                description: 'Finish the flow.',
                elementType: 'END_ELEMENT',
                icon: 'utility:stop',
                iconBackgroundColor: 'background-red',
                iconShape: 'circle',
                iconSize: 'medium',
                isSupported: true,
                label: 'End',
                section: 'Logic',
                supportsMenu: false,
                type: 'end',
                value: 'END_ELEMENT'
            },
            node: {
                config: {},
                connectorCount: 0,
                description: '',
                elementType: 'END_ELEMENT',
                guid: 'end',
                isCanvasElement: true,
                label: 'End',
                locationX: 0,
                locationY: 0,
                name: 'END_ELEMENT',
                nodeType: 'end',
                prev: 'createRecords',
                text: 'END_ELEMENT',
                value: 'END_ELEMENT'
            },
            toBeDeleted: false
        }
    ]
};

export { flowWithFault };
