// DEPRECATED: DO NOT ADD TO THIS FILE! This is going away soon. See W-8232833
export const mockActions = [
    {
        iconId: null,
        allowsTransactionControl: true,
        iconName: null,
        description: 'Add an account to the database',
        label: 'addAccount',
        type: 'externalService',
        fillColor: null,
        isStandard: false,
        name: 'BankServiceNew.addAccount',
        configurationEditor: null,
        category: 'BankServiceNew',
        genericTypes: [],
        durableId: 'externalService-BankServiceNew.addAccount'
    },
    {
        iconId: null,
        allowsTransactionControl: true,
        iconName: null,
        description: 'Given a list of Account IDs, return a list of Account names.',
        label: 'Action Test',
        type: 'apex',
        fillColor: null,
        isStandard: false,
        name: 'mynamespace__ActionTest',
        configurationEditor: null,
        genericTypes: [],
        durableId: 'apex-mynamespace__ActionTest',
        category: 'Sales'
    },
    {
        iconId: null,
        allowsTransactionControl: false,
        iconName: null,
        description: 'Activates a session-based permission set for the running user.',
        label: 'Activate Session-Based Permission Set',
        type: 'activateSessionPermSet',
        fillColor: null,
        isStandard: true,
        name: 'activateSessionPermSet',
        configurationEditor: null,
        category: 'Users',
        genericTypes: [],
        durableId: 'activateSessionPermSet-activateSessionPermSet'
    },
    {
        iconId: null,
        allowsTransactionControl: false,
        iconName: null,
        description: null,
        label: 'Add Member',
        type: 'quickAction',
        fillColor: null,
        isStandard: false,
        name: 'CollaborationGroup.mynamespace__NewGroupMember',
        configurationEditor: null,
        category: 'Group',
        genericTypes: [],
        durableId: 'quickAction-CollaborationGroup.mynamespace__NewGroupMember'
    },
    {
        iconId: null,
        allowsTransactionControl: false,
        iconName: null,
        description: null,
        label: 'Add Record',
        type: 'quickAction',
        fillColor: null,
        isStandard: false,
        name: 'CollaborationGroup.mynamespace__NewGroupRecord',
        configurationEditor: null,
        category: 'Group',
        genericTypes: [],
        durableId: 'quickAction-CollaborationGroup.mynamespace__NewGroupRecord'
    },
    {
        iconId: null,
        allowsTransactionControl: false,
        iconName: null,
        description: null,
        label: 'Change Date',
        type: 'quickAction',
        fillColor: null,
        isStandard: false,
        name: 'Task.mynamespace__Defer',
        configurationEditor: null,
        category: 'Task',
        genericTypes: [],
        durableId: 'quickAction-Task.mynamespace__Defer'
    },
    {
        iconId: null,
        allowsTransactionControl: false,
        iconName: null,
        description: null,
        label: 'Change Priority',
        type: 'quickAction',
        fillColor: null,
        isStandard: false,
        name: 'Task.mynamespace__UpdatePriority',
        configurationEditor: null,
        category: 'Task',
        genericTypes: [],
        durableId: 'quickAction-Task.mynamespace__UpdatePriority'
    },
    {
        iconId: null,
        allowsTransactionControl: false,
        iconName: null,
        description: null,
        label: 'Change Status',
        type: 'quickAction',
        fillColor: null,
        isStandard: false,
        name: 'Task.mynamespace__UpdateStatus',
        configurationEditor: null,
        category: 'Task',
        genericTypes: [],
        durableId: 'quickAction-Task.mynamespace__UpdateStatus'
    },
    {
        iconId: null,
        allowsTransactionControl: false,
        iconName: null,
        description: null,
        label: 'Create New Task',
        type: 'quickAction',
        fillColor: null,
        isStandard: false,
        name: 'FeedItem.mynamespace__NewTaskFromFeedItem',
        configurationEditor: null,
        category: 'Feed Item',
        genericTypes: [],
        durableId: 'quickAction-FeedItem.mynamespace__NewTaskFromFeedItem'
    },
    {
        iconId: null,
        allowsTransactionControl: false,
        iconName: null,
        description: 'Deactivate a session-based permission set for the running user.',
        label: 'Deactivate Session-Based Permission Set',
        type: 'deactivateSessionPermSet',
        fillColor: null,
        isStandard: true,
        name: 'deactivateSessionPermSet',
        configurationEditor: null,
        category: 'Users',
        genericTypes: [],
        durableId: 'deactivateSessionPermSet-deactivateSessionPermSet'
    },
    {
        iconId: null,
        allowsTransactionControl: false,
        iconName: null,
        description: null,
        label: 'Edit Comments',
        type: 'quickAction',
        fillColor: null,
        isStandard: false,
        name: 'Task.mynamespace__EditDescription',
        configurationEditor: null,
        category: 'Task',
        genericTypes: [],
        durableId: 'quickAction-Task.mynamespace__EditDescription'
    },
    {
        isStandard: false,
        name: 'Case.mynamespace__LogACall',
        description: null,
        label: 'Log a Call',
        type: 'quickAction',
        durableId: 'quickAction-Case.mynamespace__LogACall',
        category: 'Service'
    },
    {
        iconId: null,
        allowsTransactionControl: false,
        iconName: null,
        description: null,
        label: 'Log a Call',
        type: 'quickAction',
        fillColor: null,
        isStandard: false,
        name: 'mynamespace__LogACall',
        configurationEditor: null,
        category: 'Task',
        genericTypes: [],
        durableId: 'quickAction-mynamespace__LogACall'
    },
    {
        iconId: null,
        allowsTransactionControl: false,
        iconName: null,
        description: 'My Email Alert',
        label: 'My Email Alert',
        type: 'emailAlert',
        fillColor: null,
        isStandard: false,
        name: 'mynamespace__img_src_http_foo_bar_foo_jpg__c.mynamespace__My_Email_Alert',
        configurationEditor: null,
        category: null,
        genericTypes: [],
        durableId: 'emailAlert-mynamespace__img_src_http_foo_bar_foo_jpg__c.mynamespace__My_Email_Alert'
    },
    {
        iconId: null,
        allowsTransactionControl: false,
        iconName: null,
        description: null,
        label: 'New Account',
        type: 'quickAction',
        fillColor: null,
        isStandard: false,
        name: 'mynamespace__NewAccount',
        configurationEditor: null,
        category: 'Account',
        genericTypes: [],
        durableId: 'quickAction-mynamespace__NewAccount'
    },
    {
        iconId: null,
        allowsTransactionControl: false,
        iconName: null,
        description: null,
        label: 'New Case',
        type: 'quickAction',
        fillColor: null,
        isStandard: false,
        name: 'mynamespace__NewCase',
        configurationEditor: null,
        category: 'Case',
        genericTypes: [],
        durableId: 'quickAction-mynamespace__NewCase'
    },
    {
        iconId: null,
        allowsTransactionControl: false,
        iconName: null,
        description: null,
        label: 'New Child Case',
        type: 'quickAction',
        fillColor: null,
        isStandard: false,
        name: 'Case.mynamespace__NewChildCase',
        configurationEditor: null,
        category: 'Case',
        genericTypes: [],
        durableId: 'quickAction-Case.mynamespace__NewChildCase'
    },
    {
        iconId: null,
        allowsTransactionControl: false,
        iconName: null,
        description: null,
        label: 'New Contact',
        type: 'quickAction',
        fillColor: null,
        isStandard: false,
        name: 'mynamespace__NewContact',
        configurationEditor: null,
        category: 'Contact',
        genericTypes: [],
        durableId: 'quickAction-mynamespace__NewContact'
    },
    {
        iconId: null,
        allowsTransactionControl: false,
        iconName: null,
        description: null,
        label: 'New Event',
        type: 'quickAction',
        fillColor: null,
        isStandard: false,
        name: 'mynamespace__NewEvent',
        configurationEditor: null,
        category: 'Event',
        genericTypes: [],
        durableId: 'quickAction-mynamespace__NewEvent'
    },
    {
        iconId: null,
        allowsTransactionControl: false,
        iconName: null,
        description: null,
        label: 'New Group',
        type: 'quickAction',
        fillColor: null,
        isStandard: false,
        name: 'mynamespace__NewGroup',
        configurationEditor: null,
        category: 'Group',
        genericTypes: [],
        durableId: 'quickAction-mynamespace__NewGroup'
    },
    {
        iconId: null,
        allowsTransactionControl: false,
        iconName: null,
        description: null,
        label: 'New Lead',
        type: 'quickAction',
        fillColor: null,
        isStandard: false,
        name: 'mynamespace__NewLead',
        configurationEditor: null,
        category: 'Lead',
        genericTypes: [],
        durableId: 'quickAction-mynamespace__NewLead'
    },
    {
        iconId: null,
        allowsTransactionControl: false,
        iconName: null,
        description: null,
        label: 'New Opportunity',
        type: 'quickAction',
        fillColor: null,
        isStandard: false,
        name: 'mynamespace__NewOpportunity',
        configurationEditor: null,
        category: 'Opportunity',
        genericTypes: [],
        durableId: 'quickAction-mynamespace__NewOpportunity'
    },
    {
        iconId: null,
        allowsTransactionControl: false,
        iconName: null,
        description: null,
        label: 'New Task',
        type: 'quickAction',
        fillColor: null,
        isStandard: false,
        name: 'mynamespace__NewTask',
        configurationEditor: null,
        category: 'Task',
        genericTypes: [],
        durableId: 'quickAction-mynamespace__NewTask'
    },
    {
        iconId: null,
        allowsTransactionControl: false,
        iconName: null,
        description: null,
        label: 'Send OM',
        type: 'outboundMessage',
        fillColor: null,
        isStandard: false,
        name: 'Account.mynamespace__OM',
        configurationEditor: null,
        category: 'Outbound Message',
        genericTypes: [],
        durableId: 'outboundMessage-Account.mynamespace__OM'
    },
    {
        iconId: null,
        // this is wrong. allowsTransactionControl is actually false. But it makes some tests to fail to bring it back to its real value.
        allowsTransactionControl: true,
        iconName: null,
        description: 'Post to the feed for a specific record, user, or Chatter group.',
        label: 'Post to Chatter',
        type: 'chatterPost',
        fillColor: null,
        isStandard: true,
        name: 'chatterPost',
        configurationEditor: null,
        category: 'Messaging',
        genericTypes: [],
        durableId: 'chatterPost-chatterPost'
    },
    {
        iconId: null,
        allowsTransactionControl: false,
        iconName: null,
        description: 'Send an email where you specify the subject, body, and recipients.',
        label: 'Send Email',
        type: 'emailSimple',
        fillColor: null,
        isStandard: true,
        name: 'emailSimple',
        configurationEditor: null,
        category: 'Email',
        genericTypes: [],
        durableId: 'emailSimple-emailSimple'
    },
    {
        iconId: null,
        allowsTransactionControl: false,
        iconName: null,
        description: 'Submit a Salesforce record for approval.',
        label: 'Submit for Approval',
        type: 'submit',
        fillColor: null,
        isStandard: true,
        name: 'submit',
        configurationEditor: null,
        category: 'Approvals',
        genericTypes: [],
        durableId: 'submit-submit'
    },
    {
        iconId: null,
        allowsTransactionControl: false,
        iconName: null,
        description: 'A Lightning Component Bundle',
        label: 'successLocalAction',
        type: 'component',
        fillColor: null,
        isStandard: false,
        name: 'mynamespace:successLocalAction',
        configurationEditor: null,
        category: null,
        genericTypes: [],
        durableId: 'component-mynamespace:successLocalAction'
    }
];
