export const mockRules =
[
    {
        ruleType:'assignment',
        left:{
            paramType:'Data',
            paramIndex:1,
            dataType: 'Date',
            collection:false,
            canBeSobjectField:'CanBe',
            canBeSystemVariable:'CanBe',
            canBeElements:['VARIABLE'],
            cannotBeElements:['CHOICE', 'CHOICELOOKUP', 'CONSTANT', 'FORMULA', 'SCREENFIELD']
        },
        operator:'Assign',
        rhsParams:[
            {
                paramType:'Data',
                paramIndex:1,
                dataType: 'Date',
                collection:false,
                canBeSobjectField:'CanBe',
                canBeSystemVariable:'CanBe',
                canBeElements:['CHOICE', 'CHOICELOOKUP', 'CONSTANT', 'FORMULA', 'SCREENFIELD', 'VARIABLE'],
            },
            {
                paramType:'Data',
                paramIndex:1,
                dataType: 'DateTime',
                collection:false,
                canBeSobjectField:'CanBe',
                canBeSystemVariable:'CanBe',
                canBeElements:['CHOICE', 'CHOICELOOKUP', 'CONSTANT', 'FORMULA', 'SCREENFIELD', 'VARIABLE'],
            }
        ],
    },
    {
        ruleType:'assignment',
        left:{
            paramType:'Data',
            paramIndex:1,
            dataType: 'DateTime',
            collection:false,
            canBeSobjectField:'CanBe',
            canBeSystemVariable:'CanBe',
            canBeElements:['VARIABLE'],
            cannotBeElements:['CHOICE', 'CHOICELOOKUP', 'CONSTANT', 'FORMULA', 'SCREENFIELD']
        },
        operator:'Assign',
        rhsParams:[
            {
                paramType:'Data',
                paramIndex:1,
                dataType: 'Date',
                collection:false,
                canBeSobjectField:'CanBe',
                canBeSystemVariable:'CanBe',
                canBeElements:['CHOICE', 'CHOICELOOKUP', 'CONSTANT', 'FORMULA', 'SCREENFIELD', 'VARIABLE'],
            },
            {
                paramType:'Data',
                paramIndex:1,
                dataType: 'DateTime',
                collection:false,
                canBeSobjectField:'CanBe',
                canBeSystemVariable:'CanBe',
                canBeElements:['CHOICE', 'CHOICELOOKUP', 'CONSTANT', 'FORMULA', 'SCREENFIELD', 'VARIABLE'],
            }
        ],
        excludeElems: ['ASSIGNMENT'],
    },
    {
        ruleType:'assignment',
        left:{
            paramType:'Element',
            paramIndex:1,
            elementType:'STAGE',
            collection:true,
            canBeSobjectField:'CannotBe',
            canBeSystemVariable:'MustBe'
        },
        operator:'Equals',
        rhsParams:[
            {
                paramType:'Element',
                paramIndex:1,
                elementType:'STAGE',
                collection:false,
                canBeSobjectField:'CannotBe',
                canBeSystemVariable:'CanBe'
            }
        ]
    },
    {
        ruleType:'comparison',
        left:{
            paramType:'Element',
            paramIndex:1,
            elementType:'STAGE',
            collection:false,
            canBeSobjectField:'CannotBe',
            canBeSystemVariable:'MustBe'
        },
        operator:'Equals',
        rhsParams:[
            {
                paramType:'Element',
                paramIndex:1,
                elementType:'STAGE',
                collection:false,
                canBeSobjectField:'CannotBe',
                canBeSystemVariable:'CanBe'
            }
        ],
        excludeElems:['DECISION']
    },
    // duplicate rule needed for testing removal of duplicates.
    // there will never be a direct copy of a rule, just duplicates on LHS or Operator
    {
        ruleType:'comparison',
        left:{
            paramType:'Element',
            paramIndex:1,
            elementType:'STAGE',
            collection:false,
            canBeSobjectField:'CannotBe',
            canBeSystemVariable:'MustBe'
        },
        operator:'Equals',
        rhsParams:[
            {
                paramType:'Element',
                paramIndex:1,
                dataType:'DateTime',
                collection:false,
                canBeSobjectField:'CannotBe',
                canBeSystemVariable:'CanBe'
            }
        ]
    },
    {
        ruleType:'assignment',
        left:{
            paramType:'Data',
            paramIndex:1,
            dataType: 'SObject',
            collection:false,
            canBeSobjectField:'CannotBe',
            canBeSystemVariable:'CanBe'
        },
        operator:'Assign',
        rhsParams:[
            {
                paramType:'Data',
                paramIndex:1,
                dataType: 'SObject',
                collection:false,
                canBeSobjectField:'CanBe',
                canBeSystemVariable:'CanBe'
            }
        ]
    },
    {
        ruleType:'comparison',
        left:{
            paramType:'Element',
            paramIndex:1,
            elementType:'STAGE',
            collection:false,
            canBeSobjectField:'CannotBe',
            canBeSystemVariable:'MustBe'
        },
        operator:'Equals',
        rhsParams:[
            {
                paramType:'Element',
                paramIndex:1,
                dataType: 'DateTime',
                collection:false,
                canBeSobjectField:'CannotBe',
                canBeSystemVariable:'CanBe'
            }
        ],
    },
    {
        ruleType:'comparison',
        left:{
            paramType:'Element',
            paramIndex:1,
            elementType:'STAGE',
            collection:true,
            canBeSobjectField:'CannotBe',
            canBeSystemVariable:'MustBe'
        },
        operator:'Equals',
        rhsParams:[
            {
                paramType:'Element',
                paramIndex:1,
                dataType: 'DateTime',
                collection:true,
                canBeSobjectField:'CannotBe',
                canBeSystemVariable:'CanBe'
            }
        ],
    },
];
export const mockRulesFromServiceForAssigment = [ 
    { 
        "ruleType":"assignment", 
        "validationType":null, 
        "left":{ 
            "paramType":"Data", 
            "paramIndex":1, 
            "dataType":"String", 
            "canBeSobjectField":"CanBe", 
            "canBeSystemVariable":"CanBe", 
            "canBeElements":["VARIABLE"],
            "cannotBeElements":[ "CHOICE", "CHOICELOOKUP", "CONSTANT", "FORMULA", "SCREENFIELD", "TEXTTEMPLATE", "STAGE"], 
            "mustBeElements":[], 
            "elementType":null, 
            "collection":false 
        }, 
        "comparisonOperator":null, 
        "assignmentOperator":{ 
            "value":"Assign" 
        }, 
        "rhsParams":[ 
            { 
                "paramType":"Data", 
                "paramIndex":1, 
                "dataType":"String", 
                "canBeSobjectField":"CanBe", 
                "canBeSystemVariable":"CanBe", 
                "canBeElements":["CHOICE", "CHOICELOOKUP", "CONSTANT", "FORMULA", "SCREENFIELD", "VARIABLE"], 
                "cannotBeElements":[], 
                "mustBeElements":[], 
                "elementType":null, 
                "collection":false 
            }, 
            { 
                "paramType":"Data", 
                "paramIndex":1, 
                "dataType":"Date", 
                "canBeSobjectField":"CanBe", 
                "canBeSystemVariable":"CanBe", 
                "canBeElements":["CHOICE", "CHOICELOOKUP", "CONSTANT", "FORMULA", "SCREENFIELD", "VARIABLE"], 
                "cannotBeElements":[], 
                "mustBeElements":[], 
                "elementType":null, 
                "collection":false 
            }, 
            { 
                "paramType":"Data", 
                "paramIndex":1, 
                "dataType":"DateTime", 
                "canBeSobjectField":"CanBe", 
                "canBeSystemVariable":"CanBe", 
                "canBeElements":["CHOICE", "CHOICELOOKUP", "CONSTANT", "FORMULA", "SCREENFIELD", "VARIABLE"], 
                "cannotBeElements":[], 
                "mustBeElements":[], 
                "elementType":null, 
                "collection":false 
            }, 
            { 
                "paramType":"Data", 
                "paramIndex":1, 
                "dataType":"Number", 
                "canBeSobjectField":"CanBe", 
                "canBeSystemVariable":"CanBe", 
                "canBeElements":["CHOICE", "CHOICELOOKUP", "CONSTANT", "FORMULA", "SCREENFIELD", "VARIABLE"], 
                "cannotBeElements":[], 
                "mustBeElements":[], 
                "elementType":null, 
                "collection":false 
            }, 
            { 
                "paramType":"Data", 
                "paramIndex":1, 
                "dataType":"Currency", 
                "canBeSobjectField":"CanBe", 
                "canBeSystemVariable":"CanBe", 
                "canBeElements":["CHOICE", "CHOICELOOKUP", "CONSTANT", "FORMULA", "SCREENFIELD", "VARIABLE"], 
                "cannotBeElements":[], 
                "mustBeElements":[], 
                "elementType":null, 
                "collection":false 
            }, 
            { 
                "paramType":"Data", 
                "paramIndex":1, 
                "dataType":"Boolean", 
                "canBeSobjectField":"CanBe", 
                "canBeSystemVariable":"CanBe", 
                "canBeElements":["CHOICE", "CHOICELOOKUP", "CONSTANT", "FORMULA", "SCREENFIELD", "VARIABLE"], 
                "cannotBeElements":[], 
                "mustBeElements":[], 
                "elementType":null, 
                "collection":false 
            }, 
            { 
                "paramType":"Data", 
                "paramIndex":1, 
                "dataType":"Picklist", 
                "canBeSobjectField":"CanBe", 
                "canBeSystemVariable":"CanBe", 
                "canBeElements":["SCREENFIELD", "VARIABLE"], 
                "cannotBeElements":["CHOICE", "CHOICELOOKUP", "CONSTANT", "FORMULA"], 
                "mustBeElements":[], 
                "elementType":null, 
                "collection":false 
            }, 
            { 
                "paramType":"Data", 
                "paramIndex":1, 
                "dataType":"Multipicklist", 
                "canBeSobjectField":"CanBe", 
                "canBeSystemVariable":"CanBe", 
                "canBeElements":["SCREENFIELD", "VARIABLE"], 
                "cannotBeElements":["CHOICE", "CHOICELOOKUP", "CONSTANT", "FORMULA"], 
                "mustBeElements":[], 
                "elementType":null, 
                "collection":false 
            }, 
            { 
                "paramType":"Element", 
                "paramIndex":1, 
                "dataType":null, 
                "canBeSobjectField":"CannotBe", 
                "canBeSystemVariable":"CanBe", 
                "canBeElements":[], 
                "cannotBeElements":["CHOICE", "CHOICELOOKUP", "CONSTANT", "FORMULA", "SCREENFIELD", "VARIABLE"], 
                "mustBeElements":["STAGE"], 
                "elementType":"STAGE", 
                "collection":false 
            } 
        ], 
        "includeElems":null, 
        "excludeElems":null 
    }, 
    { 
        "ruleType":"assignment", 
        "validationType":null, 
        "left":{ 
            "paramType":"Data", 
            "paramIndex":1, 
            "dataType":"Date", 
            "canBeSobjectField":"CanBe", 
            "canBeSystemVariable":"CanBe", 
            "canBeElements":["VARIABLE"], 
            "cannotBeElements":["CHOICE", "CHOICELOOKUP", "CONSTANT", "FORMULA", "SCREENFIELD", "TEXTTEMPLATE"], 
            "mustBeElements":[], 
            "elementType":null, 
            "collection":false 
        }, 
        "comparisonOperator":null, 
        "assignmentOperator":{ 
            "value":"Assign" 
        }, 
        "rhsParams":[ 
            { 
                "paramType":"Data", 
                "paramIndex":1, 
                "dataType":"Date", 
                "canBeSobjectField":"CanBe", 
                "canBeSystemVariable":"CanBe", 
                "canBeElements":["CHOICE", "CHOICELOOKUP", "CONSTANT", "FORMULA", "SCREENFIELD", "VARIABLE"], 
                "cannotBeElements":[], 
                "mustBeElements":[], 
                "elementType":null, 
                "collection":false 
            }, 
            { 
                "paramType":"Data", 
                "paramIndex":1, 
                "dataType":"DateTime", 
                "canBeSobjectField":"CanBe", 
                "canBeSystemVariable":"CanBe", 
                "canBeElements":["CHOICE", "CHOICELOOKUP", "CONSTANT", "FORMULA", "SCREENFIELD", "VARIABLE"], 
                "cannotBeElements":[], 
                "mustBeElements":[], 
                "elementType":null, 
                "collection":false 
            } 
        ], 
        "includeElems":null, 
        "excludeElems":null 
    }, 
    { 
        "ruleType":"assignment", 
        "validationType":null, 
        "left":{ 
            "paramType":"Data", 
            "paramIndex":1, 
            "dataType":"Number", 
            "canBeSobjectField":"CanBe", 
            "canBeSystemVariable":"CanBe", 
            "canBeElements":["VARIABLE"], 
            "cannotBeElements":["CHOICE", "CHOICELOOKUP", "CONSTANT", "FORMULA", "SCREENFIELD", "TEXTTEMPLATE"], 
            "mustBeElements":[], 
            "elementType":null, 
            "collection":false 
        }, 
        "comparisonOperator":null, 
        "assignmentOperator":{ 
            "value":"Assign" 
        }, 
        "rhsParams":[ 
            { 
                "paramType":"Data", 
                "paramIndex":1, 
                "dataType":"Number", 
                "canBeSobjectField":"CanBe", 
                "canBeSystemVariable":"CanBe", 
                "canBeElements":["CHOICE", "CHOICELOOKUP", "CONSTANT", "FORMULA", "SCREENFIELD", "VARIABLE"], 
                "cannotBeElements":[], 
                "mustBeElements":[], 
                "elementType":null, 
                "collection":false 
            }, 
            { 
                "paramType":"Data", 
                "paramIndex":1, 
                "dataType":"Currency", 
                "canBeSobjectField":"CanBe", 
                "canBeSystemVariable":"CanBe", 
                "canBeElements":["CHOICE", "CHOICELOOKUP", "CONSTANT", "FORMULA", "SCREENFIELD", "VARIABLE"], 
                "cannotBeElements":[], 
                "mustBeElements":[], 
                "elementType":null, 
                "collection":false 
            } 
        ], 
        "includeElems":null, 
        "excludeElems":null 
    }, 
    { 
        "ruleType":"assignment", 
        "validationType":null, 
        "left":{ 
            "paramType":"Data", 
            "paramIndex":1, 
            "dataType":"Currency", 
            "canBeSobjectField":"CanBe", 
            "canBeSystemVariable":"CanBe", 
            "canBeElements":["VARIABLE"], 
            "cannotBeElements":["CHOICE", "CHOICELOOKUP", "CONSTANT", "FORMULA", "SCREENFIELD", "TEXTTEMPLATE"], 
            "mustBeElements":[], 
            "elementType":null, 
            "collection":false 
        }, 
        "comparisonOperator":null, 
        "assignmentOperator":{ 
            "value":"Assign" 
        }, 
        "rhsParams":[ 
            { 
                "paramType":"Data", 
                "paramIndex":1, 
                "dataType":"Number", 
                "canBeSobjectField":"CanBe", 
                "canBeSystemVariable":"CanBe", 
                "canBeElements":["CHOICE", "CHOICELOOKUP", "CONSTANT", "FORMULA", "SCREENFIELD", "VARIABLE"], 
                "cannotBeElements":[], 
                "mustBeElements":[], 
                "elementType":null, 
                "collection":false 
            }, 
            { 
                "paramType":"Data", 
                "paramIndex":1, 
                "dataType":"Currency", 
                "canBeSobjectField":"CanBe", 
                "canBeSystemVariable":"CanBe", 
                "canBeElements":["CHOICE", "CHOICELOOKUP", "CONSTANT", "FORMULA", "SCREENFIELD", "VARIABLE"], 
                "cannotBeElements":[], 
                "mustBeElements":[], 
                "elementType":null, 
                "collection":false 
            } 
        ], 
        "includeElems":null, 
        "excludeElems":null 
    }, 
    { 
        "ruleType":"assignment", 
        "validationType":null, 
        "left":{ 
            "paramType":"Data", 
            "paramIndex":1, 
            "dataType":"Boolean", 
            "canBeSobjectField":"CanBe", 
            "canBeSystemVariable":"CanBe", 
            "canBeElements":["VARIABLE"], 
            "cannotBeElements":["CHOICE", "CHOICELOOKUP", "CONSTANT", "FORMULA", "SCREENFIELD", "TEXTTEMPLATE"], 
            "mustBeElements":[], 
            "elementType":null, 
            "collection":false 
        }, 
        "comparisonOperator":null, 
        "assignmentOperator":{ 
            "value":"Assign" 
        }, 
        "rhsParams":[ 
            { 
                "paramType":"Data", 
                "paramIndex":1, 
                "dataType":"Boolean", 
                "canBeSobjectField":"CanBe", 
                "canBeSystemVariable":"CanBe", 
                "canBeElements":["CHOICE", "CHOICELOOKUP", "CONSTANT", "FORMULA", "SCREENFIELD", "VARIABLE"], 
                "cannotBeElements":[], 
                "mustBeElements":[], 
                "elementType":null, 
                "collection":false 
            } 
        ], 
        "includeElems":null, 
        "excludeElems":null 
    }, 
    { 
        "ruleType":"assignment", 
        "validationType":null, 
        "left":{ 
            "paramType":"Data", 
            "paramIndex":1, 
            "dataType":"SObject", 
            "canBeSobjectField":"CanBe", 
            "canBeSystemVariable":"CanBe", 
            "canBeElements":["VARIABLE"], 
            "cannotBeElements":["CHOICE", "CHOICELOOKUP", "CONSTANT", "FORMULA", "SCREENFIELD", "TEXTTEMPLATE"], 
            "mustBeElements":[], 
            "elementType":null, 
            "collection":false 
        }, 
        "comparisonOperator":null, 
        "assignmentOperator":{ 
            "value":"Assign" 
        }, 
        "rhsParams":[ 
            { 
                "paramType":"Data", 
                "paramIndex":1, 
                "dataType":"SObject", 
                "canBeSobjectField":"CanBe", 
                "canBeSystemVariable":"CanBe", 
                "canBeElements":["CHOICE", "CHOICELOOKUP", "CONSTANT", "FORMULA", "SCREENFIELD", "TEXTTEMPLATE"], 
                "cannotBeElements":[], 
                "mustBeElements":[], 
                "elementType":null, 
                "collection":false 
            } 
        ], 
        "includeElems":null, 
        "excludeElems":null 
    }, 
    { 
        "ruleType":"assignment", 
        "validationType":null, 
        "left":{ 
            "paramType":"Data", 
            "paramIndex":1, 
            "dataType":"String", 
            "canBeSobjectField":"CanBe", 
            "canBeSystemVariable":"CannotBe", 
            "canBeElements":["CHOICE", "CHOICELOOKUP", "CONSTANT", "FORMULA", "SCREENFIELD", "VARIABLE"], 
            "cannotBeElements":[], 
            "mustBeElements":[], 
            "elementType":null, 
            "collection":true 
        }, 
        "comparisonOperator":null, 
        "assignmentOperator":{ 
            "value":"Assign" 
        }, 
        "rhsParams":[ 
            { 
                "paramType":"Data", 
                "paramIndex":1, 
                "dataType":"String", 
                "canBeSobjectField":"CanBe", 
                "canBeSystemVariable":"CannotBe", 
                "canBeElements":["CHOICE", "CHOICELOOKUP", "CONSTANT", "FORMULA", "SCREENFIELD", "VARIABLE"], 
                "cannotBeElements":[], 
                "mustBeElements":[], 
                "elementType":null, 
                "collection":true 
            }, 
            { 
                "paramType":"Data", 
                "paramIndex":1, 
                "dataType":"Picklist", 
                "canBeSobjectField":"CanBe", 
                "canBeSystemVariable":"CanBe", 
                "canBeElements":["SCREENFIELD", "VARIABLE"], 
                "cannotBeElements":["CHOICE", "CHOICELOOKUP", "CONSTANT", "FORMULA"], 
                "mustBeElements":[], 
                "elementType":null, 
                "collection":true 
            }, 
            { 
                "paramType":"Data", 
                "paramIndex":1, 
                "dataType":"Multipicklist", 
                "canBeSobjectField":"CanBe", 
                "canBeSystemVariable":"CanBe", 
                "canBeElements":["SCREENFIELD", "VARIABLE"], 
                "cannotBeElements":[ "CHOICE", "CHOICELOOKUP", "CONSTANT", "FORMULA"], 
                "mustBeElements":[], 
                "elementType":null, 
                "collection":true 
            } 
        ], 
        "includeElems":null, 
        "excludeElems":null 
    }, 
    { 
        "ruleType":"assignment", 
        "validationType":null, 
        "left":{ 
            "paramType":"Data", 
            "paramIndex":1, 
            "dataType":"String", 
            "canBeSobjectField":"CanBe", 
            "canBeSystemVariable":"CannotBe", 
            "canBeElements":["CHOICE", "CHOICELOOKUP", "CONSTANT", "FORMULA", "SCREENFIELD", "VARIABLE"], 
            "cannotBeElements":[], 
            "mustBeElements":[], 
            "elementType":null, 
            "collection":true 
        }, 
        "comparisonOperator":null, 
        "assignmentOperator":{ 
            "value":"Assign" 
        }, 
        "rhsParams":[ 
            { 
                "paramType":"Element", 
                "paramIndex":1, 
                "dataType":null, 
                "canBeSobjectField":"CannotBe", 
                "canBeSystemVariable":"MustBe", 
                "canBeElements":[], 
                "cannotBeElements":["CHOICE", "CHOICELOOKUP", "CONSTANT", "FORMULA", "SCREENFIELD", "VARIABLE"], 
                "mustBeElements":["STAGE"], 
                "elementType":"STAGE", 
                "collection":true 
            } 
        ], 
        "includeElems":null, 
        "excludeElems":["SUBFLOW"] 
    }, 
    { 
        "ruleType":"assignment", 
        "validationType":null, 
        "left":{ 
            "paramType":"Data", 
            "paramIndex":1, 
            "dataType":"Date", 
            "canBeSobjectField":"CanBe", 
            "canBeSystemVariable":"CanBe", 
            "canBeElements":["CHOICE", "CHOICELOOKUP", "CONSTANT", "FORMULA", "SCREENFIELD", "VARIABLE"], 
            "cannotBeElements":[], 
            "mustBeElements":[], 
            "elementType":null, 
            "collection":true 
        }, 
        "comparisonOperator":null, 
        "assignmentOperator":{ 
            "value":"Assign" 
        }, 
        "rhsParams":[ 
            { 
                "paramType":"Data", 
                "paramIndex":1, 
                "dataType":"Date", 
                "canBeSobjectField":"CanBe", 
                "canBeSystemVariable":"CanBe", 
                "canBeElements":["CHOICE", "CHOICELOOKUP", "CONSTANT", "FORMULA", "SCREENFIELD", "VARIABLE"], 
                "cannotBeElements":[], 
                "mustBeElements":[], 
                "elementType":null, 
                "collection":true 
            } 
        ], 
        "includeElems":null, 
        "excludeElems":null 
    }, 
    { 
        "ruleType":"assignment", 
        "validationType":null, 
        "left":{ 
            "paramType":"Data", 
            "paramIndex":1, 
            "dataType":"Number", 
            "canBeSobjectField":"CanBe", 
            "canBeSystemVariable":"CanBe", 
            "canBeElements":["CHOICE", "CHOICELOOKUP", "CONSTANT", "FORMULA", "SCREENFIELD", "VARIABLE"], 
            "cannotBeElements":[], 
            "mustBeElements":[], 
            "elementType":null, 
            "collection":true 
        }, 
        "comparisonOperator":null, 
        "assignmentOperator":{ 
            "value":"Assign" 
        }, 
        "rhsParams":[ 
            { 
                "paramType":"Data", 
                "paramIndex":1, 
                "dataType":"Number", 
                "canBeSobjectField":"CanBe", 
                "canBeSystemVariable":"CanBe", 
                "canBeElements":["CHOICE", "CHOICELOOKUP", "CONSTANT", "FORMULA", "SCREENFIELD", "VARIABLE"], 
                "cannotBeElements":[], 
                "mustBeElements":[], 
                "elementType":null, 
                "collection":true 
            } 
        ], 
        "includeElems":null, 
        "excludeElems":null 
    }, 
    { 
        "ruleType":"assignment", 
        "validationType":null, 
        "left":{ 
            "paramType":"Data", 
            "paramIndex":1, 
            "dataType":"Boolean", 
            "canBeSobjectField":"CanBe", 
            "canBeSystemVariable":"CanBe", 
            "canBeElements":["CHOICE", "CHOICELOOKUP", "CONSTANT", "FORMULA", "SCREENFIELD", "VARIABLE"], 
            "cannotBeElements":[], 
            "mustBeElements":[], 
            "elementType":null, 
            "collection":true 
        }, 
        "comparisonOperator":null, 
        "assignmentOperator":{ 
            "value":"Assign" 
        }, 
        "rhsParams":[ 
            { 
                "paramType":"Data", 
                "paramIndex":1, 
                "dataType":"Boolean", 
                "canBeSobjectField":"CanBe", 
                "canBeSystemVariable":"CanBe", 
                "canBeElements":["CHOICE", "CHOICELOOKUP", "CONSTANT", "FORMULA", "SCREENFIELD", "VARIABLE"], 
                "cannotBeElements":[], 
                "mustBeElements":[], 
                "elementType":null, 
                "collection":true 
            } 
        ], 
        "includeElems":null, 
        "excludeElems":null 
    }, 
    { 
        "ruleType":"assignment", 
        "validationType":null, 
        "left":{ 
            "paramType":"Data", 
            "paramIndex":1, 
            "dataType":"SObject", 
            "canBeSobjectField":"CanBe", 
            "canBeSystemVariable":"CanBe", 
            "canBeElements":["VARIABLE"], 
            "cannotBeElements":["CHOICE", "CHOICELOOKUP", "CONSTANT", "FORMULA", "SCREENFIELD", "TEXTTEMPLATE"], 
            "mustBeElements":[], 
            "elementType":null, 
            "collection":true 
        }, 
        "comparisonOperator":null, 
        "assignmentOperator":{ 
            "value":"Assign" 
        }, 
        "rhsParams":[ 
            { 
                "paramType":"Data", 
                "paramIndex":1, 
                "dataType":"SObject", 
                "canBeSobjectField":"CanBe", 
                "canBeSystemVariable":"CanBe", 
                "canBeElements":["CHOICE", "CHOICELOOKUP", "CONSTANT", "FORMULA", "SCREENFIELD", "VARIABLE"], 
                "cannotBeElements":[], 
                "mustBeElements":[], 
                "elementType":null, 
                "collection":true 
            } 
        ], 
        "includeElems":null, 
        "excludeElems":null 
    } 
];