// to update elementsForPropertyEditors from flowWithAllElementsUIModel, run propertyEditorFactory.test.ts and follow instructions
export const elementsForPropertyEditors = {
    stringVariable: {
        guid: '27cfbe21-2aa1-4503-aa13-3677c687153d',
        name: { value: 'stringVariable', error: null },
        description: { value: 'random description', error: null },
        elementType: 'Variable',
        isCollection: false,
        isInput: false,
        isOutput: false,
        dataType: { value: 'String', error: null },
        subtype: { value: null, error: null },
        subtypeIndex: { value: '583e40d5-e735-4d8c-8f30-097d48de7ec8', error: null },
        scale: 0,
        defaultValue: { value: 'fooDefault', error: null },
        defaultValueDataType: { value: 'String', error: null },
        defaultValueIndex: { value: 'e41bbbb0-08ee-40bf-ab4a-810a34f151a1', error: null }
    },
    numberVariable: {
        guid: '42afe63b-0744-4dec-a7e6-20c67691dd81',
        name: { value: 'numberVariable', error: null },
        description: { value: '', error: null },
        elementType: 'Variable',
        isCollection: false,
        isInput: false,
        isOutput: false,
        dataType: { value: 'Number', error: null },
        subtype: { value: null, error: null },
        subtypeIndex: { value: '02504510-b361-4fb3-878e-81925a76160f', error: null },
        scale: 2,
        defaultValue: { value: null, error: null },
        defaultValueDataType: { value: null, error: null },
        defaultValueIndex: { value: '26b1d461-e66e-41c7-bb0e-5c86b04280db', error: null }
    },
    dateVariable: {
        guid: '3d47c47d-df60-4f92-85c8-71982afd9938',
        name: { value: 'dateVariable', error: null },
        description: { value: '', error: null },
        elementType: 'Variable',
        isCollection: false,
        isInput: false,
        isOutput: false,
        dataType: { value: 'Date', error: null },
        subtype: { value: null, error: null },
        subtypeIndex: { value: 'cea1a8e6-1cb0-4b2f-9549-2610c8b61f78', error: null },
        scale: 0,
        defaultValue: { value: null, error: null },
        defaultValueDataType: { value: null, error: null },
        defaultValueIndex: { value: 'b2eef3a8-57d5-42b7-ad31-c9923cd8a782', error: null }
    },
    stringCollectionVariable1: {
        guid: '2e02687e-41a2-42eb-ba74-81c130218b86',
        name: { value: 'stringCollectionVariable1', error: null },
        description: { value: '', error: null },
        elementType: 'Variable',
        isCollection: true,
        isInput: false,
        isOutput: false,
        dataType: { value: 'String', error: null },
        subtype: { value: null, error: null },
        subtypeIndex: { value: 'c9f73d4d-7d65-41bd-b1b6-f6e8b47cef56', error: null },
        scale: 0,
        defaultValue: { value: null, error: null },
        defaultValueDataType: { value: null, error: null },
        defaultValueIndex: { value: '52bc2460-8775-417b-a692-f72725a8f6b0', error: null }
    },
    accountSObjectVariable: {
        guid: '60f7e7ac-6177-4f7c-843d-6ebb0b9bd929',
        name: { value: 'accountSObjectVariable', error: null },
        description: { value: '', error: null },
        elementType: 'Variable',
        isCollection: false,
        isInput: false,
        isOutput: false,
        dataType: { value: 'SObject', error: null },
        subtype: { value: 'Account', error: null },
        subtypeIndex: { value: 'ecf6b72e-f33e-48a4-a58c-bdcc87a80e40', error: null },
        scale: 0,
        defaultValue: { value: null, error: null },
        defaultValueDataType: { value: null, error: null },
        defaultValueIndex: { value: '3147a31d-26a3-408c-b00b-a31983df0da5', error: null }
    },
    textTemplate1: {
        guid: '1669c1f5-9872-461f-a826-b4fa64d902dd',
        name: { value: 'textTemplate1', error: null },
        description: { value: '', error: null },
        elementType: 'TextTemplate',
        text: { value: '<p>Hello {!stringVariable}</p>', error: null },
        dataType: { value: 'String', error: null },
        isViewedAsPlainText: false
    },
    textTemplate2: {
        guid: '9c51615d-c61a-46f7-b26a-7157f6908b21',
        name: { value: 'textTemplate2', error: null },
        description: { value: '', error: null },
        elementType: 'TextTemplate',
        text: { value: 'This text template is in plain text mode.', error: null },
        dataType: { value: 'String', error: null },
        isViewedAsPlainText: true
    },
    stringConstant: {
        guid: 'f317c423-f755-4d64-bd4a-e218107b57db',
        name: { value: 'stringConstant', error: null },
        description: { value: 'random description', error: null },
        elementType: 'Constant',
        dataType: { value: 'String', error: null },
        defaultValue: { value: 'fooDefault', error: null },
        defaultValueDataType: { value: 'String', error: null },
        defaultValueIndex: { value: '794b3296-5246-473a-b618-584b8956809c', error: null }
    },
    emailScreenField: {
        guid: 'c3ba5281-2d20-4596-99d0-94b9368c1d70',
        name: { value: 'emailScreenField', error: null },
        choiceReferences: [],
        defaultValue: { value: '', error: null },
        defaultValueIndex: { value: 'acbbb552-1389-4ec3-9807-d8c3aa378d70', error: null },
        validationRule: { formulaExpression: { value: null, error: null }, errorMessage: { value: null, error: null } },
        extensionName: { value: 'flowruntime:email', error: null },
        fieldType: { value: 'ComponentInstance', error: null },
        fieldText: { value: '', error: null },
        helpText: { value: '', error: null },
        inputParameters: [
            {
                rowIndex: 'ac2ad112-16a7-4f97-bb41-7d5a0a41679f',
                name: { value: 'label', error: null },
                value: { value: 'emailScreenField', error: null },
                valueDataType: { value: 'String', error: null }
            },
            {
                rowIndex: 'fd06f9e3-6e63-4d89-b441-ca4c0594deb5',
                name: { value: 'placeholder', error: null },
                value: { value: 'your email', error: null },
                valueDataType: { value: 'String', error: null }
            }
        ],
        isNewField: false,
        isRequired: true,
        outputParameters: [],
        scale: { value: '0', error: null },
        type: {
            name: { value: 'flowruntime:email', error: null },
            fieldType: { value: 'ComponentInstance', error: null },
            label: { value: 'flowruntime:email', error: null },
            icon: { value: 'standard:lightning_component', error: null },
            source: { value: 'local', error: null }
        },
        elementType: 'SCREEN_FIELD',
        visibilityRule: { conditions: [], conditionLogic: { value: 'no_conditions', error: null } },
        fields: [],
        inputsOnNextNavToAssocScrn: 'UseStoredValues',
        dynamicTypeMappings: [],
        storeOutputAutomatically: false
    },
    emailScreenFieldAutomaticOutput: {
        guid: '865e456d-2e1d-410f-8c62-8f686238b197',
        name: { value: 'emailScreenFieldAutomaticOutput', error: null },
        choiceReferences: [],
        dataType: { value: 'LightningComponentOutput', error: null },
        defaultValue: { value: '', error: null },
        defaultValueIndex: { value: '6f3f842a-e289-48ee-b18b-6820e87cee94', error: null },
        validationRule: { formulaExpression: { value: null, error: null }, errorMessage: { value: null, error: null } },
        extensionName: { value: 'flowruntime:email', error: null },
        fieldType: { value: 'ComponentInstance', error: null },
        fieldText: { value: '', error: null },
        helpText: { value: '', error: null },
        inputParameters: [
            {
                rowIndex: 'f876df5e-ccc8-43a5-921f-4730c6c8052b',
                name: { value: 'label', error: null },
                value: { value: 'emailScreenFieldAutomaticOutput', error: null },
                valueDataType: { value: 'String', error: null }
            },
            {
                rowIndex: 'f9efafa3-d83f-41a6-92e8-487eadb228c0',
                name: { value: 'placeholder', error: null },
                value: { value: 'your email address', error: null },
                valueDataType: { value: 'String', error: null }
            }
        ],
        isNewField: false,
        isRequired: true,
        outputParameters: [],
        scale: { value: '0', error: null },
        type: {
            name: { value: 'flowruntime:email', error: null },
            fieldType: { value: 'ComponentInstance', error: null },
            label: { value: 'flowruntime:email', error: null },
            icon: { value: 'standard:lightning_component', error: null },
            source: { value: 'local', error: null }
        },
        elementType: 'SCREEN_FIELD',
        visibilityRule: { conditions: [], conditionLogic: { value: 'no_conditions', error: null } },
        fields: [],
        inputsOnNextNavToAssocScrn: 'UseStoredValues',
        dynamicTypeMappings: [],
        storeOutputAutomatically: true
    },
    deleteAccountWithFilters: {
        guid: '3980ef9a-c9c0-4635-a6af-13682830ba4b',
        name: { value: 'deleteAccountWithFilters', error: null },
        description: { value: '', error: null },
        label: { value: 'deleteAccountWithFilters', error: null },
        locationX: 1213,
        locationY: 832,
        isCanvasElement: true,
        connectorCount: 0,
        config: { isSelected: false, isHighlighted: false, isSelectable: true, hasError: false },
        inputReference: { value: '', error: null },
        inputReferenceIndex: { value: '8232343e-c77f-4502-9234-793bc5470183', error: null },
        object: { value: 'Account', error: null },
        objectIndex: { value: '2c2b6727-f892-4a27-802c-8414e7f162de', error: null },
        filterLogic: { value: '(1 AND 2) OR 3', error: null },
        filters: [
            {
                rowIndex: 'fde9b89d-7177-4303-889d-5293eaeb58aa',
                leftHandSide: { value: 'Account.BillingCity', error: null },
                rightHandSide: { value: '60f7e7ac-6177-4f7c-843d-6ebb0b9bd929.BillingCity', error: null },
                rightHandSideDataType: { value: 'reference', error: null },
                operator: { value: 'EqualTo', error: null }
            },
            {
                rowIndex: '1219bee3-aea6-4567-b155-e5ddb4a543bd',
                leftHandSide: { value: 'Account.BillingCountry', error: null },
                rightHandSide: { value: 'USA', error: null },
                rightHandSideDataType: { value: 'String', error: null },
                operator: { value: 'EqualTo', error: null }
            },
            {
                rowIndex: '35837efc-fe6e-4096-8de3-a00443b93527',
                leftHandSide: { value: 'Account.Name', error: null },
                rightHandSide: { value: 'SalesForce', error: null },
                rightHandSideDataType: { value: 'String', error: null },
                operator: { value: 'EqualTo', error: null }
            }
        ],
        maxConnections: 2,
        availableConnections: [{ type: 'REGULAR' }, { type: 'FAULT' }],
        elementType: 'RecordDelete',
        dataType: { value: 'Boolean', error: null },
        useSobject: false
    },
    deleteAccount: {
        guid: '5a93e09a-856a-4540-a62f-239f61d7de50',
        name: { value: 'deleteAccount', error: null },
        description: { value: '', error: null },
        label: { value: 'deleteAccount', error: null },
        locationX: 955,
        locationY: 469,
        isCanvasElement: true,
        connectorCount: 0,
        config: { isSelected: false, isHighlighted: false, isSelectable: true, hasError: false },
        inputReference: { value: '60f7e7ac-6177-4f7c-843d-6ebb0b9bd929', error: null },
        inputReferenceIndex: { value: 'e46d1655-6558-4c7b-b828-b040906115b0', error: null },
        object: { value: '', error: null },
        objectIndex: { value: '134b1c72-cb94-4987-806d-155a8cc0f736', error: null },
        filterLogic: { value: 'and', error: null },
        filters: [],
        maxConnections: 2,
        availableConnections: [{ type: 'REGULAR' }, { type: 'FAULT' }],
        elementType: 'RecordDelete',
        dataType: { value: 'Boolean', error: null },
        useSobject: true
    },
    other: {
        guid: '1a024e7c-0ada-4ab4-8211-9e3b1a4e9836',
        name: { value: 'other', error: null },
        description: { value: '', error: null },
        elementType: 'Choice',
        dataType: { value: 'String', error: null },
        choiceText: { value: 'Other', error: null },
        storedValue: { value: 'other', error: null },
        storedValueDataType: { value: 'String', error: null },
        storedValueIndex: { value: 'f4b58a0a-045d-49d4-b1c7-888e895a4484', error: null },
        isShowInputSelected: true,
        isValidateSelected: false,
        userInput: { isRequired: false, promptText: { value: 'Please specify', error: null } }
    }
};
