export const emptyFlow = {
        createdById: "005xx000001X7i5AAC",
        createdDate: "2018-12-19T15:49:05.000+0000",
        definitionId: "300xx000000bnevAAA",
        fieldsToNull: [],
        fullName: "Empty_Flow",
        id: "301xx000003GZ7zAAG",
        lastModifiedBy: {fieldsToNull: Array(0), name: "User User"},
        lastModifiedById: "005xx000001X7i5AAC",
        lastModifiedDate: "2018-12-19T15:49:09.000+0000",
        manageableState: "unmanaged",
        masterLabel: "Empty Flow",
        metadata: {
            actionCalls: [],
            apexPluginCalls: [],
            assignments: [],
            choices: [],
            constants: [],
            decisions: [],
            dynamicChoiceSets: [],
            formulas: [],
            interviewLabel: "Empty Flow {!$Flow.CurrentDateTime}",
            isTemplate: false,
            label: "Empty Flow",
            loops: [],
            processMetadataValues: [{
                name: "BuilderType",
                value: {stringValue: "LightningFlowBuilder"}
                }, {
                    name: "OriginBuilderType",
                    value: {stringValue: "LightningFlowBuilder"}
            }],
            processType: "AutoLaunchedFlow",
            recordCreates: [],
            recordDeletes: [],
            recordLookups: [],
            recordUpdates: [],
            screens: [],
            stages: [],
            status: "Draft",
            steps: [],
            subflows: [],
            textTemplates: [],
            variables: [],
            waits: [],
        },
        processType: "AutoLaunchedFlow",
        status: "Draft",
        versionNumber: 1
};